version: "3"
services:
  puppeteer-node:
    image: kou029w/puppeteer-node
    build:
      context: github.com/puppeteer/puppeteer#:.ci/node12
      dockerfile: Dockerfile.linux
  sync-codesandbox:
    image: kou029w/sync-codesandbox
    build:
      context: "."
    depends_on: [puppeteer-node]
